RESTAURANTS = [ "1/4 Lb Big Burger",
                "A-Burger",
                "All American Burgers",
                "Anny's Fine Burger",
                "Bd Burgers",
                "Bergies Burger Stop",
                "Betty Burgers",
                "Big G Burger",
                "Big Mouth Burgers",
                "Bill's Burgers",
                "Bistro Burger",
                "Boy's Hamburgers 8",
                "Bravo Burgers & Tacos",
                "Brooks Burgers",
                "Bulls Eye Burgers & Brew",
                "Burger 355",
                "Burger Basket",
                "Burger Boss",
                "Burger Factory",
                "Burger Hut",
                "Burger Junction",
                "Burger Palace",
                "Burger Pit",
                "Burger Road",
                "Burger Station",
                "Burgers Plus",
                "Ca Burger",
                "Canada Steakburger",
                "Casa Burger Drive-In",
                "Christos Best Burgers",
                "Cowboy Burgers & Bbq",
                "Cypress Best Burgers",
                "Dinos Burgers",
                "Eddie's Star Burger",
                "Fabolous Burgers",
                "Fuji's Famous Burger",
                "GD Bro Burger",
                "George's Burgers",
                "Gold Star Hamburgers",
                "Gyros Burger & More",
                "Hashtag Burgers",
                "Haven Burgers",
                "Heintz Burgers",
                "Hook Burger",
                "Hot Burger",
                "House Burger",
                "Jack's Junior World Famous Burgers",
                "Jim's Burgers",
                "JJ's Burger Joint",
                "John's Burger"
                "Johnny's Burgers 3",
                "Judys Burger",
                "Julio's Burgers",
                "Jurupa Super Burger",
                "Kalbi Burger",
                "Krush Burger",
                "La Garza Burgers & More",
                "Leo S Burger",
                "Mad Dogz And Burgers",
                "Main Street Burgers",
                "Manuel’s Burgers",
                "Master Burger No 3",
                "Mega Tom's Burgers",
                "MGM Burgers",
                "Michael's Burgers",
                "Mo Burger",
                "Mojo Burger",
                "Nany's Burgers",
                "Nikko's Burgers",
                "Nom Burger",
                "Orcutt Burgers",
                "P & G Burgers",
                "Penny's Burgers",
                "Perry Burger",
                "Queens Burgers",
                "R Burgers",
                "Riverwalk Burger",
                "Sail-Thru Hamburgers",
                "Sasa's Burgers",
                "Simon's Burger",
                "Star Burgers",
                "Super Burger",
                "Tam's Burgers",
                "Ted's Burger",
                "Teri Burger Bernie's",
                "The Burger Joint",
                "The Spot Teriyaki And Burgers",
                "Tk Burgers Viii",
                "Tom's Burgers",
                "Tom's Jrs Burgers",
                "Triple A Burger",
                "Umami Burger",
                "Varsity Burgers",
                "Weekend Dreams Burgers And More",
                "Willy J's Burgers & More",
                "Woody's Breakfast & Burgers",
                "Yummy Burger",
                "Zorba's Burgers"]