RESTAURANTS = ['Big Mouth Burgers',
               'Burger Station',
               'Super Burger',
               'Burger Basket',
               'Burger Factory',
               'Cypress Best Burgers',
               'Gold Star Hamburgers',
               'Hook Burger',
               'Burger Palace',
               'Varsity Burgers',
               'Burger Boss',
               'P & G Burgers',
               'R Burgers',
               'Betty Burgers']