# -*- coding: utf-8 -*-
"""Web Scraping Uber Eats Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tvkkOyS1SPHmvTgPdqxD_opPnYrSPEma
"""

from urllib.request import urlopen
import pandas as pd

url = "https://www.ubereats.com/store/mcdonalds-milpitas-blvd/4PzdUBUtQSOdn2KsPbRBpQ"
#url = "https://www.ubereats.com/store/taco-bell-774-s-main-st/8gJ9-pJgTpuwPJpOlDXtpg"
page = urlopen(url)
html = page.read().decode("utf-8")

format = r"{\"@type\":\"MenuItem\",\"name\":\"(.+?)\",\"description\":\".*?\",\"offers\":{\"@type\":\"Offer\",\"price\":\"(\d+\.\d+)\",\"priceCurrency\":\"USD\"}}"

import re

c = re.findall(format, html)

print(type(c))
print(len(c))

for a, b in c:
  print(a, b)

d = dict(c)

for key in d:
  print(key, d[key])

data = pd.DataFrame(c, columns = ["Menu Item", "Price"])
data["Restaurant"] = "McDonald's"
data["Location"] = "Milpitas Blvd"
data